default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kuroko2
  password: kuroko2
  host: 127.0.0.1

development:
  <<: *default
  database: kuroko2
